echo "Now to use any file, type cd Termux-Setup"
echo "then type bash <filename>"
echo "Files and functions present:"
echo "[*] Basic Setup: bash basicSetup.sh"
echo "[*] Termux Header: bash termuxBanner.sh"
echo "[*] Termux OS: bash termuxOS.sh"
echo "[*] Hacking tools: bash hackerTools"
echo "[*] Debian in Termux: bash termuxDebian.sh"
echo "[*] Nethunter in Termux: bash termuxNethunter.sh"
echo "[*] Ubuntu in Termux: bash termuxUbuntu.sh"
echo "[*] Styling Addon: bash termuxStyling.sh"